version: '3.8'

services:
  arenapos:
    build: .
    container_name: arenapos
    restart: always
    ports:
      - "5050:5050"
    volumes:
      - arenapos_data:/app/apps/api/prisma
    environment:
      - NODE_ENV=production
      - API_PORT=5050
      - USE_HTTPS=false
      - JWT_SECRET=supersecret
      - CORS_ORIGIN=*
      - TELEGRAM_BOT_TOKEN=8539140642:AAHoTNdn-y4I2sxswotPLNCMWlckwNPHEp8
      - TELEGRAM_CHAT_ID=-1003416454746
      - HTTPS_PROXY=
    networks:
      - arena-net

volumes:
  arenapos_data:

networks:
  arena-net:
    driver: bridge
